import Foundation
import Testing
@testable import TurboFieldfare

/// `K3ChatRenderer` against golden XTML fixtures generated by the official
/// `encoding_k3.py`: for each of the 13 conversations the rendered text and
/// the full token stream must match exactly. The conversations mirror the
/// fixture generator's inputs one-to-one.
@Suite struct K3ChatRendererTests {

    private struct XTMLCase: Decodable {
        let text: String
        let ids: [Int]
        let name: String
    }

    private static func fixtureURL(_ name: String) throws -> URL {
        try #require(Bundle.module.url(
            forResource: name,
            withExtension: nil,
            subdirectory: "Fixtures/k3"))
    }

    private static let sharedTokenizer: Result<K3Tokenizer, Error> = Result {
        try K3Tokenizer(vocabURL: fixtureURL("tiktoken.model"))
    }

    private static let sharedCases: Result<[XTMLCase], Error> = Result {
        try JSONDecoder().decode(
            [XTMLCase].self,
            from: Data(contentsOf: fixtureURL("xtml_fixtures.json")))
    }

    private func tokenizer() throws -> K3Tokenizer {
        try Self.sharedTokenizer.get()
    }

    private func fixture(_ name: String) throws -> XTMLCase {
        let cases = try Self.sharedCases.get()
        return try #require(cases.first { $0.name == name }, "missing fixture \(name)")
    }

    /// The two tool specs used by the fixture generator.
    private static let tools: [K3ToolDeclaration] = [
        K3ToolDeclaration(
            name: "get_weather",
            description: "Get the current weather for a city.",
            parameters: .object([
                "type": .string("object"),
                "properties": .object([
                    "city": .object(["type": .string("string")]),
                ]),
                "required": .array([.string("city")]),
            ])),
        K3ToolDeclaration(
            name: "search_docs",
            description: "Search internal docs.",
            parameters: .object([
                "type": .string("object"),
                "properties": .object([
                    "query": .object(["type": .string("string")]),
                    "limit": .object(["type": .string("integer")]),
                ]),
                "required": .array([.string("query")]),
            ])),
    ]

    private static func user(_ content: String, name: String? = nil) -> K3ChatMessage {
        K3ChatMessage(role: .user, content: .text(content), name: name)
    }

    private static func system(_ content: String) -> K3ChatMessage {
        K3ChatMessage(role: .system, content: .text(content))
    }

    // MARK: - Golden fixture cases

    @Test func systemUser() throws {
        try check("system_user", messages: [
            Self.system("You are a helpful assistant."),
            Self.user("What is the capital of France?"),
        ])
    }

    @Test func userOnly() throws {
        try check("user_only", messages: [
            Self.user("안녕하세요"),
        ])
    }

    @Test func noThinking() throws {
        try check("no_thinking", messages: [
            Self.user("Say hi."),
        ], options: K3ChatOptions(thinking: false))
    }

    @Test func effortLow() throws {
        try check("effort_low", messages: [
            Self.system("Be terse."),
            Self.user("2+2?"),
        ], options: K3ChatOptions(thinkingEffort: .low))
    }

    @Test func effortMax() throws {
        try check("effort_max", messages: [
            Self.user("Prove sqrt(2) is irrational."),
        ], options: K3ChatOptions(thinkingEffort: .max))
    }

    @Test func multiTurnWithThinking() throws {
        try check("multi_turn_with_thinking", messages: [
            Self.user("Hi"),
            K3ChatMessage(
                role: .assistant,
                content: .text("Hello! How can I help?"),
                reasoningContent: "User greeted me casually."),
            Self.user("What is 17 * 23?"),
        ])
    }

    @Test func toolsDeclared() throws {
        try check("tools_declared", messages: [
            Self.system("You can call tools."),
            Self.user("Weather in Seoul?"),
        ], options: K3ChatOptions(tools: Self.tools))
    }

    @Test func toolLoop() throws {
        // Tool results arrive out of call order; the renderer re-sorts them
        // against the assistant tool_calls by tool_call_id.
        try check("tool_loop", messages: [
            Self.user("Weather in Seoul and Busan?"),
            K3ChatMessage(
                role: .assistant,
                content: .text("Let me check both."),
                reasoningContent: "Need two weather calls.",
                toolCalls: [
                    K3ToolCall(id: "call_0", name: "get_weather",
                               arguments: .jsonString("{\"city\": \"Seoul\"}")),
                    K3ToolCall(id: "call_1", name: "get_weather",
                               arguments: .jsonString("{\"city\": \"Busan\"}")),
                ]),
            K3ChatMessage(role: .tool, content: .text("{\"temp\": 26}"),
                          toolCallID: "call_1"),
            K3ChatMessage(role: .tool, content: .text("{\"temp\": 25}"),
                          toolCallID: "call_0"),
        ], options: K3ChatOptions(tools: Self.tools))
    }

    @Test func toolChoiceRequired() throws {
        try check("tool_choice_required", messages: [
            Self.user("Search for Kimi K3."),
        ], options: K3ChatOptions(tools: Self.tools, toolChoice: .required))
    }

    @Test func responseJSON() throws {
        try check("response_json", messages: [
            Self.user("Give me a JSON object with a name field."),
        ], options: K3ChatOptions(responseFormat: .jsonObject))
    }

    @Test func namedUserAndParts() throws {
        try check("named_user_and_parts", messages: [
            K3ChatMessage(role: .user,
                          content: .parts(["Hello ", "from parts"]),
                          name: "yongjin"),
        ])
    }

    @Test func jsonSchema() throws {
        try check("json_schema", messages: [
            Self.user("Extract: name, age."),
        ], options: K3ChatOptions(responseFormat: .jsonSchema(.object([
            "type": .string("object"),
            "properties": .object([
                "name": .object(["type": .string("string")]),
                "age": .object(["type": .string("integer")]),
            ]),
        ]))))
    }

    @Test func noGenerationPrompt() throws {
        try check("no_generation_prompt", messages: [
            Self.user("Partial"),
        ], options: K3ChatOptions(addGenerationPrompt: false))
    }

    private func check(
        _ name: String,
        messages: [K3ChatMessage],
        options: K3ChatOptions = .init()
    ) throws {
        let expected = try fixture(name)
        let segments = try K3ChatRenderer.buildSegments(messages: messages, options: options)
        let rendered = segments.map(\.text).joined()
        #expect(rendered == expected.text,
                "\(name): rendered text mismatch: \(Self.firstTextDivergence(rendered, expected.text))")
        // render() is the same string via the convenience path.
        #expect(try K3ChatRenderer.render(messages: messages, options: options)
                == rendered)

        let ids = try K3ChatRenderer.renderToIDs(
            messages: messages, options: options, tokenizer: tokenizer())
        #expect(ids == expected.ids,
                "\(name): token stream mismatch: \(Self.firstIDDivergence(ids, expected.ids))")
    }

    // MARK: - Focused semantics not pinned by fixtures

    @Test func attributeValuesAreEscaped() throws {
        let rendered = try K3ChatRenderer.render(messages: [
            Self.user("hi", name: "a&\"b"),
        ])
        #expect(rendered.contains(#"name="a&amp;&quot;b""#))
    }

    @Test func unresolvedToolRunIsLeftUntouched() throws {
        // No matching tool_call ids: order and messages pass through as-is.
        let messages: [K3ChatMessage] = [
            K3ChatMessage(role: .assistant, content: .text("calling"), toolCalls: [
                K3ToolCall(id: "call_0", name: "get_weather"),
            ]),
            K3ChatMessage(role: .tool, content: .text("second"),
                          tool: "get_weather", toolCallID: "mystery_b"),
            K3ChatMessage(role: .tool, content: .text("first"),
                          tool: "get_weather", toolCallID: "mystery_a"),
        ]
        let rendered = try K3ChatRenderer.render(messages: messages)
        let second = try #require(rendered.range(of: "second"))
        let first = try #require(rendered.range(of: "first"))
        #expect(second.lowerBound < first.lowerBound)
        // Unmatched runs keep their explicit tool names and arrival indexes.
        #expect(rendered.contains(#"index="1""#))
        #expect(rendered.contains(#"index="2""#))
    }

    @Test func unparseableArgumentsRenderAsJSONBlock() throws {
        let rendered = try K3ChatRenderer.render(messages: [
            K3ChatMessage(role: .assistant, content: .text("calling"), toolCalls: [
                K3ToolCall(id: "call_0", name: "get_weather",
                           arguments: .jsonString("not json at all")),
            ]),
        ])
        #expect(rendered.contains(
            "<|open|>json type=\"object\"<|sep|>not json at all<|close|>json<|sep|>"))
    }

    @Test func nonObjectArgumentsThrow() throws {
        #expect(throws: K3ChatRendererError.nonObjectToolArguments) {
            try K3ChatRenderer.render(messages: [
                K3ChatMessage(role: .assistant, content: .text("calling"), toolCalls: [
                    K3ToolCall(id: "call_0", name: "get_weather",
                               arguments: .jsonString("[1, 2, 3]")),
                ]),
            ])
        }
    }

    @Test func toolMessageWithoutNameThrows() throws {
        #expect(throws: K3ChatRendererError.unresolvableToolName) {
            try K3ChatRenderer.render(messages: [
                K3ChatMessage(role: .tool, content: .text("orphan")),
            ])
        }
    }

    @Test func toolNameFallsBackToCallOrder() throws {
        let rendered = try K3ChatRenderer.render(messages: [
            K3ChatMessage(role: .assistant, content: .text("calling"), toolCalls: [
                K3ToolCall(name: "get_weather"),
            ]),
            K3ChatMessage(role: .tool, content: .text("sunny")),
        ])
        #expect(rendered.contains(#"tool="get_weather" index="1""#))
    }

    @Test func dynamicToolDeclareOnSystemMessage() throws {
        let rendered = try K3ChatRenderer.render(messages: [
            K3ChatMessage(role: .system, tools: Self.tools),
            Self.user("hi"),
        ])
        #expect(rendered.contains("type=\"tool-declare\""))
        #expect(rendered.contains("## New Tools Available"))
        #expect(rendered.contains("\"name\":\"search_docs\""))
    }

    @Test func nonThinkingDropsThinkChannel() throws {
        let messages = [
            Self.user("Hi"),
            K3ChatMessage(role: .assistant,
                          content: .text("Hello!"),
                          reasoningContent: "Some reasoning."),
        ]
        let thinking = try K3ChatRenderer.render(messages: messages)
        #expect(thinking.contains("<|open|>think<|sep|>Some reasoning.<|close|>think<|sep|>"))
        let notThinking = try K3ChatRenderer.render(
            messages: messages, options: K3ChatOptions(thinking: false))
        #expect(!notThinking.contains("think"))
        #expect(notThinking.contains(
            "<|open|>message role=\"assistant\"<|sep|><|open|>response<|sep|>"))
    }

    @Test func toolCallIndexAttributeEscapesAndArgumentTypes() throws {
        let rendered = try K3ChatRenderer.render(messages: [
            K3ChatMessage(role: .assistant, content: .text("calling"), toolCalls: [
                K3ToolCall(name: "fn", arguments: .object(.object([
                    "count": .integer(3),
                    "ok": .bool(true),
                    "tags": .array([.string("a"), .string("b")]),
                ]))),
            ]),
        ])
        #expect(rendered.contains(#"argument key="count" type="number""#))
        #expect(rendered.contains(#"argument key="ok" type="boolean""#))
        #expect(rendered.contains(#"argument key="tags" type="array""#))
        // Non-string argument values render via json.dumps default spacing.
        #expect(rendered.contains(#"["a", "b"]"#))
    }

    private static func firstTextDivergence(_ actual: String, _ expected: String) -> String {
        if actual == expected { return "" }
        let pairs = zip(actual.indices, expected.indices)
        for (a, b) in pairs where actual[a] != expected[b] {
            let context = actual[a...].prefix(40)
            let expectedContext = expected[b...].prefix(40)
            return "first divergence at \(actual.distance(from: actual.startIndex, to: a)): "
                + "got \(String(context).debugDescription), "
                + "want \(String(expectedContext).debugDescription)"
        }
        return "length mismatch: got \(actual.count), want \(expected.count)"
    }

    private static func firstIDDivergence(_ actual: [Int], _ expected: [Int]) -> String {
        let count = min(actual.count, expected.count)
        for i in 0..<count where actual[i] != expected[i] {
            return "first divergence at \(i): got \(actual[i]), want \(expected[i])"
        }
        if actual.count != expected.count {
            return "count mismatch: got \(actual.count), want \(expected.count)"
        }
        return ""
    }
}
