import Foundation
import Testing
@testable import TurboFieldfare

/// `K3Tokenizer` against golden fixtures generated by the official Python
/// implementation (`tokenization_kimi.py` + tiktoken over the real
/// `tiktoken.model`). Covers both encode modes, special-token decode, and a
/// lenient encode-performance guard.
@Suite struct K3TokenizerTests {

    private struct TokenizerFixtures: Decodable {
        struct EncodeCase: Decodable {
            let text: String
            let ids_allow_special: [Int]
            let ids_plain: [Int]
        }
        struct DecodeCase: Decodable {
            let ids: [Int]
            let text_special_decoded: String
        }
        let encode: [EncodeCase]
        let decode: [DecodeCase]
    }

    private static func fixtureURL(_ name: String) throws -> URL {
        try #require(Bundle.module.url(
            forResource: name,
            withExtension: nil,
            subdirectory: "Fixtures/k3"))
    }

    /// The vocabulary is 2.8 MB; parse it once for the whole suite.
    private static let sharedTokenizer: Result<K3Tokenizer, Error> = Result {
        try K3Tokenizer(vocabURL: fixtureURL("tiktoken.model"))
    }

    private static let sharedFixtures: Result<TokenizerFixtures, Error> = Result {
        try JSONDecoder().decode(
            TokenizerFixtures.self,
            from: Data(contentsOf: fixtureURL("tokenizer_fixtures.json")))
    }

    private func tokenizer() throws -> K3Tokenizer {
        try Self.sharedTokenizer.get()
    }

    private func fixtures() throws -> TokenizerFixtures {
        try Self.sharedFixtures.get()
    }

    @Test func vocabShapeAndNamedIDs() throws {
        let tokenizer = try tokenizer()
        #expect(tokenizer.vocabSize == 163_840)
        #expect(K3Tokenizer.baseVocabSize == 163_584)
        #expect(K3Tokenizer.specialSlotCount == 256)

        #expect(tokenizer.bosID == 163_584)
        #expect(tokenizer.eosID == 163_585)
        #expect(tokenizer.endOfMessageID == 163_586)
        #expect(tokenizer.openID == 163_587)
        #expect(tokenizer.closeID == 163_588)
        #expect(tokenizer.sepID == 163_589)
        #expect(tokenizer.startHeaderID == 163_590)
        #expect(tokenizer.endHeaderID == 163_591)
        #expect(tokenizer.eotID == 163_593)
        #expect(tokenizer.mediaBeginID == 163_602)
        #expect(tokenizer.mediaContentID == 163_603)
        #expect(tokenizer.mediaEndID == 163_604)
        #expect(tokenizer.mediaPadID == 163_605)
        #expect(tokenizer.osAgentModeID == 163_649)
        #expect(tokenizer.unkID == 163_838)
        #expect(tokenizer.padID == 163_839)

        #expect(tokenizer.specialID(forName: "<|open|>") == 163_587)
        #expect(tokenizer.specialID(forName: "[BOS]") == 163_584)
        #expect(tokenizer.specialID(forName: "<|reserved_token_163592|>") == 163_592)
        #expect(tokenizer.specialID(forName: "<|reserved_token_163837|>") == 163_837)
        #expect(tokenizer.specialID(forName: "hello") == nil)
        #expect(tokenizer.specialName(forID: 163_589) == "<|sep|>")
        #expect(tokenizer.specialName(forID: 163_700) == "<|reserved_token_163700|>")
        #expect(tokenizer.specialName(forID: 42) == nil)
    }

    @Test func encodeAllowSpecialMatchesFixtures() throws {
        let tokenizer = try tokenizer()
        let cases = try fixtures().encode
        #expect(cases.count == 36)
        for (index, fixture) in cases.enumerated() {
            let ids = try tokenizer.encode(fixture.text, allowSpecial: true)
            #expect(ids == fixture.ids_allow_special,
                    "case \(index) \(Self.preview(fixture.text)): \(Self.firstDivergence(ids, fixture.ids_allow_special))")
        }
    }

    @Test func encodePlainMatchesFixtures() throws {
        let tokenizer = try tokenizer()
        for (index, fixture) in try fixtures().encode.enumerated() {
            let ids = try tokenizer.encode(fixture.text, allowSpecial: false)
            #expect(ids == fixture.ids_plain,
                    "case \(index) \(Self.preview(fixture.text)): \(Self.firstDivergence(ids, fixture.ids_plain))")
        }
    }

    @Test func decodeMatchesFixtures() throws {
        let tokenizer = try tokenizer()
        let cases = try fixtures().decode
        #expect(cases.count == 20)
        for (index, fixture) in cases.enumerated() {
            let text = tokenizer.decode(fixture.ids)
            #expect(text == fixture.text_special_decoded,
                    "decode case \(index): \(Self.preview(text))")
        }
    }

    @Test func decodeEncodeRoundTripForPlainTexts() throws {
        let tokenizer = try tokenizer()
        for (index, fixture) in try fixtures().encode.enumerated() {
            let ids = try tokenizer.encode(fixture.text, allowSpecial: false)
            #expect(tokenizer.decode(ids) == fixture.text,
                    "round-trip case \(index) \(Self.preview(fixture.text))")
        }
    }

    @Test func decodeSpecialIDsEmitLiteralNames() throws {
        let tokenizer = try tokenizer()
        #expect(tokenizer.decode([163_587]) == "<|open|>")
        #expect(tokenizer.decode([163_584, 163_585]) == "[BOS][EOS]")
        #expect(tokenizer.decode([163_592]) == "<|reserved_token_163592|>")
        // Unknown ids are out of vocabulary; they degrade to U+FFFD.
        #expect(tokenizer.decode([163_840]) == "\u{FFFD}")
    }

    @Test func emptyAndSingleByteEdges() throws {
        let tokenizer = try tokenizer()
        #expect(try tokenizer.encode("") == [])
        #expect(try tokenizer.encode("", allowSpecial: false) == [])
        #expect(tokenizer.decode([]) == "")
        // Every byte value round-trips through single-byte tokens.
        let allBytes = String(decoding: (0...255).map { $0 }, as: UTF8.self)
        let ids = try tokenizer.encode(allBytes, allowSpecial: false)
        #expect(tokenizer.decode(ids) == allBytes)
    }

    @Test func encodeKoreanWithinPerformanceBudget() throws {
        let tokenizer = try tokenizer()
        var text = ""
        while text.utf8.count < 1024 {
            text += "안녕하세요 세계, 반갑습니다. 오늘도 좋은 하루 되세요. "
        }
        #expect(text.utf8.count >= 1024)
        let clock = ContinuousClock()
        let start = clock.now
        let ids = try tokenizer.encode(text, allowSpecial: false)
        let elapsed = clock.now - start
        #expect(!ids.isEmpty)
        // Guard, not a benchmark: lenient bound for a debug test binary.
        #expect(elapsed < .milliseconds(50), "1 KB Korean encode took \(elapsed)")
    }

    private static func preview(_ text: String) -> String {
        let truncated = text.prefix(40)
        return String(truncated).debugDescription
    }

    private static func firstDivergence(_ actual: [Int], _ expected: [Int]) -> String {
        let count = min(actual.count, expected.count)
        for i in 0..<count where actual[i] != expected[i] {
            return "first divergence at \(i): got \(actual[i]), want \(expected[i])"
        }
        if actual.count != expected.count {
            return "count mismatch: got \(actual.count), want \(expected.count)"
        }
        return ""
    }
}
